# Generated by Django 6.0.5 on 2026-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=5000)),
                ('about', models.TextField()),
                ('specilization', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=500)),
            ],
        ),
    ]
